### ISSUE TITLE
[Incompatible Model Crash] Half-Life 2 Models with Source 2010.

### ISSUE THREAD

**Issue by AgentAgrimar** [Enhanced-Source-Project/Enhanced-Source#36] opened 2017-12-08 16:20 UTC
While trying to use HL2 models, I've noticed crashing, I'm pretty positive it's due to incompatible models however the crash is not specific to what model is causing it even when using the debugger.

I've figured out that the Citizen models are causing crashes and probably the Zombies' too, but there appears to be others.

Is there any other way to find out what these other models are?

**Comment by Juesto** [comment] 2017-12-08 23:37
it is probably model specific, try developer 2 with a debugger attached or use -condebug (file is console.log in your game dir),  in the debugger i recommend loading the PDBs for accuracy purposes and optionally src path so you can find it in code

**Comment by AgentAgrimar** [comment] 2017-12-08 23:40
It's the engine that is crashing, so I doubt that there would be any PDBs for it, but I'll try out those commands and see how they turn out.

**Comment by Juesto** [comment] 2017-12-09 00:48
90% of code is in mod binaries (client/server) and compile produces pdb of them

**Comment by Joshua-Ashton** [comment] 2017-12-09 00:58
The issue is to do with the .vtx not being .dx90.vtx es in the VPK/NotVPK or vice versa. I can never remember the correct way around.

**Comment by AgentAgrimar** [comment] 2017-12-09 00:59
The crashes were happening at engine level, beyond the client/server binaries.
Anyway looking at the console log, it could be crashing because of a missing shader, but I'm not too sure that's it.

```
Loading: models/Monk.mdl
Loading models/Monk.mdl
Loading virtual model for monk.mdl
Loading models/monk_animations.mdl
Loading models/Humans/male_shared.mdl
Error: Material "models/monk/pupil_r" uses unknown shader "Eyeball"
Error: Material "models/monk/pupil_l" uses unknown shader "Eyeball"
```

**Comment by Joshua-Ashton** [comment] 2017-12-09 01:08
I literally just told you why it crashes.

**Comment by AgentAgrimar** [comment] 2017-12-09 01:13
@Joshua-Ashton You posted your comment while I was making my last one.

Is the last thing seen in the console log after a crash an indication of the model that's causing the crashing?
All I need to know is the model name, I've known about the .vtx thing.

**Comment by Joshua-Ashton** [comment] 2017-12-09 02:10
No

**Comment by DasMaddi** [comment] 2019-04-06 17:29
closing per known difference with model formats between asw and hl2

**Closed by DasMaddi** 2019-04-06 17:29 UTC
